services:
  java_app:
    container_name: container-java-2
    image: imagen-java
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://container-cerrado-postgres-2:5432/postgres
      - DATABASE_USERNAME=postgres 
      - DATABASE_PASSWORD=password
      - JWT_SECRET=clave123
    depends_on:
      java_db:
        condition: service_healthy

  java_db:
      container_name: container-cerrado-postgres-2
      image: postgres
      environment:
        - POSTGRES_PASSWORD=password
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 5s
        timeout: 5s
        retries: 10

networks:
  backed:
    driver: bridge
